//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool.
//     Runtime version: 4.0.30319.18444
//
//     Changes to this file may result in incorrect behavior and if
//     Regenerate the code and these changes will be lost.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsertypeDefTools.Properties
{


	/// <summary>
	///   A strongly typed resource class for finding localized strings, and so on.
	/// </summary>
	// This class is made up of StronglyTypedResourceBuilder
	// Classes are automatically generated by tools like ResGen or Visual Studio.
	// To add or remove members, edit the .ResX file and re-run ResGen
	// (Use /str as a command option) or regenerate the VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if( ( resourceMan == null ) )
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "UsertypeDefTools.Properties.Resources", typeof( Resources ).Assembly );
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Override the current thread&#39;s CurrentUICulture property for all resource lookups,
		///   The method is to use this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}
	}
}
